name = "mailone"
main = "src/index.js"
compatibility_date = "2026-02-25"

[[d1_databases]]
binding = "DB"
database_name = "mailone"
database_id = "YOUR_D1_DATABASE_ID"

[triggers]
crons = ["0 * * * *"]
